import { Inter } from "next/font/google";
import { SettingsProvider } from "@/settingsContext";
import Header from "@/components/header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

function RootLayout({ children }) {
  let component = (
    <SettingsProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </SettingsProvider>
  );

  return component;
}

export default RootLayout;
